version: '3.3'
services:
  app:
    build: 
      context: .
      target: "${TARGET:-developer}"
    env_file:
      - .env
    volumes:
      - ${PWD:-./}:/app
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db

  db:
    image: mariadb:10.6.4
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-toor}
      MARIADB_DATABASE: ${DB_NAME:-example_db}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: sh -c 'echo "[client]\nuser=root\npassword=$${DB_PASSWORD:-toor}" > /root/.my.cnf && docker-entrypoint.sh mysqld'
    ports:
      - 3306:3306

  maildev:
    image: maildev/maildev
    ports:
      - "8025:1080"
      - "25:1025"

  redis:
    image: "redis:7-alpine"
    command: "redis-server --requirepass ${REDIS_PASSWORD:-secret}"
    ports:
      - "6379:6379"

  minio:
    image: 'minio/minio:RELEASE.2023-05-04T21-44-30Z'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_ACCESS_KEY}
    entrypoint: sh
    command: -c 'mkdir ./minio/data/${S3_BUCKET_NAME}; minio server /minio/data'
    volumes:
      - data:/minio/data

volumes:
  data:
